import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/globals.css'
import Navigation from '@/components/layouts/navigation'
import { DateRangeProvider } from '@/providers/date-range-provider'
import { SessionProvider } from 'next-auth/react'
import { ResponsiveLayoutProvider } from '@/providers/responsive-layout-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen bg-neutral text-textColors-primary antialiased`}
      >
        <SessionProvider>
          <ResponsiveLayoutProvider>
            <DateRangeProvider>
              <Navigation />
              <main className="flex-1 overflow-auto px-10 py-6 sm:ml-64">{children}</main>
            </DateRangeProvider>
          </ResponsiveLayoutProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
