import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/globals.css'
import Sidebar from '@/components/sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen bg-neutral text-textColors-primary`}
      >
        <Sidebar />
        <main className="flex-1 sm:ml-64 rounded-3xl py-8 pr-8 overflow-auto">
          <div className="container bg-white h-full p-8 rounded-3xl">{children}</div>
        </main>
      </body>
    </html>
  )
}
